### PR TITLE
Local patching

### PR DESCRIPTION
**Pull request by vext01**
- don't require a capability
- attach as /dev/cpu/*/rmsr
- default permissions 660

Works for me (tm).

### CODE REVIEW

**Comment by ltratt** [comment]
File uses tabs for indentation :/

**Comment by vext01** [comment]
This.

**Comment by ltratt** [comment]
Looks good. Squash and then I can merge?

**Comment by vext01** [comment]
Ready

**Comment by vext01** [comment]
Quick off the mark Laurie!

**Pull request merged**
